name: Restore cached node dependencies

runs:
  using: "composite"
  steps:
    - name: Restore node_modules
      uses: actions/cache/restore@v4
      with:
        path: ./node_modules
        key: "${{ runner.os }}-node_modules-${{ env.NODE_VERSION }}-${{ hashFiles('./package-lock.json') }}-${{ hashFiles('**/schema.prisma') }}"
    - name: Restore e2e node_modules
      uses: actions/cache/restore@v4
      with:
        path: ./e2e/node_modules
        key: "${{ runner.os }}-node_modules_e2e-${{ env.NODE_VERSION }}-${{ hashFiles('./e2e/package-lock.json') }}"
